### ISSUE TITLE
Graceful shutdown and client keep-alive

### ISSUE THREAD

**Issue by dgrijalva** [ngmoco/falcore#14]
The serve loop is currently very generous with clients that use keep-alive.  This is, I think, a good thing, but it means the server can never gracefully shut down if there are long lived keep-alives.

I think the graceful shutdown procedure should be finish up any in flight requests and close connections as gracefully as possible.  I can see a very clean approach to this by using a separate (permanent or temporary) go routine for reading.  This will double the number of goroutines per connection, but it will also allow us to support http pipelining as we can separate read from write.

Any thoughts?  Too much?

**Comment by smw1218** [comment]
We already have the handler go routine for reading and writing the socket, and since HTTP pipelining requires in-order request-response cycles, I don't see a good reason to separate the read and write to the socket.

If we want to get multiple requests in-flight, I could see executing the pipline in it's own go routine. Then waiting on each response channel in-order without blocking.
Is that what you mean? 

In any case, I don't really see this being a huge bang-for-the-buck unless the pipeline time >> network IO time.

**Comment by dgrijalva** [comment]
Here's the issue I'm trying to solve immediately:

I have two falcore apps.  One is a router using falcore/upstream.  The other is an application server running on another box.  I can't gracefully restart my app server since the app server's falcore will wait forever for existing connections to close and the router's falcore/upstream will hold the connection open forever.

It seems falcore, once it's stopped accepting, should finish any in flight requests, then start closing connections.  

Have a look at the pull request I posted.  It's not really ready to land, but it illustrates what I'm going for.  I couldn't figure out how to break out of an idle ReadRequest.  Using a timeout could result in splitting a request in half on the wire and killing a perfectly happy connection when we're not in the shutdown case.

**Comment by smw1218** [comment]
This is resolved
