### ISSUE TITLE
SimpleResponse and other response helpers

### ISSUE THREAD

**Issue by dgrijalva** [ngmoco/falcore#25]
I'd like to propose we rename SimpleResponse to StringResponse.  We can then add a BytesResponse with similar behavior.  I'd also like to add a JSONResponse helper that takes an interface{} and returns (*http.Response, error).  There's already a pull request for a RedirectResponse helper.

These are extremely common cases and we should support them.  Renaming SimpleResponse might be painful, but it will be more clear.  We could leave it as is for now, but it seems better to just go for it...

Thoughts?

**Comment by smw1218** [comment]
I tend to think that "Simple" would imply "String" so doing an alias of some sort would be optimal.  I agree that we should rename it with "String" so that it's consistent as Response types proliferate.

This wouldn't be hard to change since I know what you're changing.  It might be more difficult for others who aren't necessarily following the project closely.  Maybe you could look at writing a gofix extension for it.

**Comment by dgrijalva** [comment]
I'll submit a thing that aliases and deprecates "Simple".  Then we can discuss how best to phase out deprecated stuff.

**Comment by dgrijalva** [comment]
Fixed in fitstar/falcore
